### ISSUE TITLE
sample.py hangs / does not work

### ISSUE THREAD

**Issue by radiocontrolled** [zytedata/zyte-smartproxy-selenium#3]
I've got a trial subscription & API key. When I run the following (after installing   zyte_smartproxy_selenium) nothing happens: 
```
from zyte_smartproxy_selenium import webdriver

browser = webdriver.Chrome(spm_options={'spm_apikey': 'mykey'})
browser.get('https://toscrape.com')
browser.save_screenshot('screenshot.png')
browser.close()
```
I'm not sure what's going on - thanks

**Comment by geronsv** [comment]
Hi @radiocontrolled 
By default `block_ads_lists` was using `['https://easylist.to/easylist/easylist.txt', 'https://easylist.to/easylist/easyprivacy.txt']`. Those urls have got some issues recently. We have now switched default value to mirrors: `['https://secure.fanboy.co.nz/easylist.txt', 'https://secure.fanboy.co.nz/easyprivacy.txt']`.
Could you try to downloading the new release?
